package de.hda.fbi.db2.stud.gui;


import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;


import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;


/**
 *
 */

@SuppressFBWarnings({"UWF_NULL_FIELD", "NP_UNWRITTEN_FIELD", "UR_UNINIT_READ"
        , "UWF_UNWRITTEN_FIELD"})

public class ResultGUI extends JFrame {
    private JTextField startTimeTextPane;
    private JTextField endTimeTextPane;
    private JButton exitButton;
    private JLabel greetingsLabel;
    private JLabel startTimeTextPane1;
    private JLabel endTimeTextPane1;
    private JLabel numberLabel;
    private JPanel panelMain;

    private static ResultGUI resultGUI = null;

    public ResultGUI() {
        super("Result");
        setContentPane(panelMain);
        pack();
        setVisible(true);
        getMainFrame().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getMainFrame().dispose();
            }
        });
    }

    public JPanel getPanelMain() {
        return panelMain;
    }

    public JLabel getGreetingsLabel() {
        return greetingsLabel;
    }

    public void setGreetingsLabel(JLabel greetingsLabel) {
        this.greetingsLabel = greetingsLabel;
    }

    public JTextField getStartTimeTextPane() {
        return startTimeTextPane;
    }

    public void setStartTimeTextPane(JTextField startTimeTextPane) {
        this.startTimeTextPane = startTimeTextPane;
    }

    public JTextField getEndTimeTextPane() {
        return endTimeTextPane;
    }

    public void setEndTimeTextPane(JTextField endTimeTextPane) {
        this.endTimeTextPane = endTimeTextPane;
    }

    public JLabel getNumberLabel() {
        return numberLabel;
    }

    public void setNumberLabel(JLabel numberLabel) {
        this.numberLabel = numberLabel;
    }

    public static ResultGUI getResultGUI() {
        if (resultGUI == null) {
            resultGUI = new ResultGUI();
        }

        return resultGUI;
    }

    private JFrame getMainFrame() {
        return (JFrame) SwingUtilities.getWindowAncestor(this.panelMain);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        setupUI();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void setupUI() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(6, 5, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Ergebnis");
        panelMain.add(label1, new GridConstraints(0, 0, 1, 5,
                GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelMain.add(spacer1, new GridConstraints(1, 4, 2, 1,
                GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                GridConstraints.SIZEPOLICY_WANT_GROW,
                null, null, null, 0, false));
        greetingsLabel = new JLabel();
        greetingsLabel.setText("Hello, Player");
        panelMain.add(greetingsLabel, new GridConstraints(1, 0, 1, 4,
                GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Score :");
        panelMain.add(label2, new GridConstraints(2, 0, 1, 2,
                GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                null, null, null, 0, false));
        startTimeTextPane1 = new JLabel();
        startTimeTextPane1.setText("Start time:");
        panelMain.add(startTimeTextPane1, new GridConstraints(3, 0, 1, 1,
                GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                null, null, null, 0, false));
        startTimeTextPane = new JTextField();
        panelMain.add(startTimeTextPane, new GridConstraints(3, 1, 1, 2,
                GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED,
                null, new Dimension(150, -1), null, 0, false));
        endTimeTextPane1 = new JLabel();
        endTimeTextPane1.setText("End time :");
        panelMain.add(endTimeTextPane1, new GridConstraints(4, 0, 1, 1,
                GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                null, null, null, 0, false));
        endTimeTextPane = new JTextField();
        panelMain.add(endTimeTextPane, new GridConstraints(4, 1, 1, 2,
                GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED,
                null, new Dimension(150, -1), null, 0, false));
        numberLabel = new JLabel();
        numberLabel.setText("Label");
        panelMain.add(numberLabel, new GridConstraints(2, 2, 1, 1,
                GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                null, null, null, 0, false));
        exitButton = new JButton();
        exitButton.setText("Exit");
        panelMain.add(exitButton, new GridConstraints(5, 2, 1, 1,
                GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED,
                null, null, null, 0, false));
    }


    /**
     * @noinspection ALL
     */
    public JComponent getRootComponent() {
        return panelMain;
    }



}
