package de.hda.fbi.db2.stud;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.*;

import org.junit.Test;

/**
 * MainTest Class.
 * @author S. Ruehl
 */ 
public class MainTest {
    @Test public void testMainHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
